name: Build LinuxRA02

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.c'
      - '**.h'
      - '**.py'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.c'
      - '**.h'
      - '**.py'
  workflow_dispatch:
    inputs:
      ld_loader_path:
        description: Path to LD Loader on target machine
        required: false
        default: "/lib/ld-linux-aarch64.so.1"
      ext_send_recv_logs:
        description: Extended logs upon sending/receiving packets
        required: false
        default: 0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'

    - name: Setup Compiler
      run: |
        sudo apt install gcc-aarch64-linux-gnu

    - name: Configure
      run: |
        export PATH="$PATH"
        cmake -B build -S . -G "Unix Makefiles"
      env:
        LD_LOADER_PATH: ${{ inputs.ld_loader_path }}
        USE_RA02_EXT_LOG_SEND_RECV: ${{ inputs.ext_send_recv_logs }}

    - name: Build
      run: cmake --build build

    - name: Archive driver library artifact
      uses: actions/upload-artifact@v4
      with:
        name: sx1278-library-so
        path: build/liblinux-sx1278.so

    - name: Archive python bindings artifact
      uses: actions/upload-artifact@v4
      with:
        name: sx1278-py
        path: bindings/sx1278.py
